/// <reference types="vite/client" />

interface Window {
  elix: {
    hasNativeTitleBar?: boolean;
    isWindows?: boolean;
    minimize: () => Promise<void>;
    maximize: () => Promise<boolean>;
    close: () => Promise<void>;
    setWindowTitle: (title: string) => Promise<void>;
    isWindowMaximized?: () => Promise<boolean>;
    setTitleBarOverlay?: (options: { color?: string; symbolColor?: string }) => Promise<boolean>;
    onWindowStateChange?: (callback: (data: { isMaximized: boolean }) => void) => () => void;
    getSystemInfo?: () => {
      version: string;
      platform: string;
      arch: string;
      electron: string;
      node: string;
      chrome: string;
      v8: string;
    };
    openFolderDialog: () => Promise<string | null>;
    getCategories: () => Promise<any[]>;
    addCategory: (cat: any) => Promise<any>;
    updateCategory: (id: string, updates: any) => Promise<any>;
    deleteCategory: (id: string) => Promise<boolean>;
    getProjects: () => Promise<any[]>;
    saveProject: (project: any) => Promise<void>;
    createProjectFromTemplate: (params: any) => Promise<any>;
    readDir: (dirPath: string) => Promise<{ name: string; isDirectory: boolean; path: string }[]>;
    readFile: (filePath: string) => Promise<string | null>;
    readFileBase64: (filePath: string) => Promise<string | null>;
    getFileStats: (filePath: string) => Promise<{ size: number; mtime: number; birthtime: number; isFile: boolean } | null>;
    writeFile: (filePath: string, content: string) => Promise<boolean>;
    createFile: (filePath: string) => Promise<boolean>;
    createDir: (dirPath: string) => Promise<boolean>;
    deleteFile: (targetPath: string) => Promise<boolean>;
    renameFile: (oldPath: string, newPath: string) => Promise<boolean>;
    revealInExplorer: (targetPath: string) => Promise<boolean>;
    openExternal: (urlOrPath: string) => Promise<boolean>;
    openFileDialog: () => Promise<string | null>;
    getLanIp: () => Promise<string>;
    getClipboardText: () => Promise<string>;
    setClipboardText: (text: string) => Promise<boolean>;
    run: (req: any) => Promise<void>;
    stop: () => Promise<void>;
    restart: (req: any) => Promise<void>;
    isRunning: () => Promise<boolean>;
    setConnectionState: (state: string) => Promise<void>;
    onExecutionEvent: (callback: (event: any) => void) => () => void;
    getEnvironments: () => Promise<any[]>;
    scanEnvironments: () => Promise<{ environments: any[]; summary: string; foundCount: number }>;
    installEnvironment: (id: string, method?: 'winget' | 'browser') => Promise<{ success: boolean; message: string }>;
    uninstallEnvironment: (id: string) => Promise<{ success: boolean; message: string }>;
    repairEnvironment: (id: string) => Promise<{ success: boolean; message: string }>;
    onEnvProgress: (callback: (data: any) => void) => () => void;
    getQuestions: (filter?: any) => Promise<any[]>;
    getQuestionById: (id: string) => Promise<any>;
    getPracticeStats: () => Promise<any>;
    recordSubmission: (sub: any) => Promise<any>;
    runPracticeTests: (req: any) => Promise<any>;
    getSubmissions: (questionId?: string) => Promise<any[]>;
    resetPracticeProgress: () => Promise<{ success: boolean; message: string }>;
    setPracticeGoal: (goal: any) => Promise<any>;
    getPracticeGoals: () => Promise<any[]>;
    getStreaks: () => Promise<Record<string, any>>;
    getActivities: (filter?: any) => Promise<any[]>;
    getHackathons: () => Promise<any[]>;
    saveHackathon: (hackathon: any) => Promise<void>;
    deleteHackathon: (id: string) => Promise<boolean>;
    getGitStatus: (repoPath: string) => Promise<any>;
    stageFile: (repoPath: string, file: string) => Promise<boolean>;
    unstageFile: (repoPath: string, file: string) => Promise<boolean>;
    commitGit: (repoPath: string, message: string) => Promise<any>;
    getGitDiff: (repoPath: string, file?: string) => Promise<string>;
    getGitLog: (repoPath: string, limit?: number) => Promise<any[]>;
    initGit: (repoPath: string) => Promise<boolean>;
    pushGit: (repoPath: string, remote?: string, branch?: string) => Promise<{ success: boolean; output?: string; error?: string }>;
    pullGit: (repoPath: string, remote?: string, branch?: string) => Promise<{ success: boolean; output?: string; error?: string }>;
    cloneGit: (repoUrl: string, targetParentDir: string) => Promise<{ success: boolean; projectPath?: string; error?: string }>;
    processAiMessage: (req: any) => Promise<any>;
    applyAiFileChange: (filePath: string, content: string) => Promise<boolean>;
    transcribeAudio: (base64Audio: string, mimeType: string) => Promise<{ success: boolean; text?: string; error?: string }>;
    getAiConfig: () => Promise<any>;
    updateAiConfig: (cfg: any) => Promise<any>;
    getTimeMachineSnapshots: (projectId: string) => Promise<any[]>;
    takeSnapshot: (params: any) => Promise<any>;
    restoreSnapshot: (params: any) => Promise<boolean>;
    getAllTemplates: () => Promise<any[]>;
    getTemplatesByCategory: (cat: string) => Promise<any[]>;
    createTerminalSession: (id: string, cwd: string, onData: (data: string) => void) => void;
    writeTerminal: (id: string, data: string) => Promise<void>;
    killTerminal: (id: string) => Promise<void>;
    getGithubCredential: () => Promise<{ username: string; token: string } | null>;
  };
}
